"""Init vault performance model

Revision ID: 3533c6e4d016
Revises: fefc717a2225
Create Date: 2024-03-09 15:31:59.416017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3533c6e4d016"
down_revision: Union[str, None] = "fefc717a2225"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vault_performance",
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("total_locked_value", sa.Float(), nullable=False),
        sa.Column("apy_1m", sa.Float(), nullable=False),
        sa.Column("apy_1w", sa.Float(), nullable=False),
        sa.Column("benchmark", sa.Float(), nullable=False),
        sa.Column("pct_benchmark", sa.Float(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vault_performance")
    # ### end Alembic commands ###
