"""Init user position table

Revision ID: 4d9e109ab04b
Revises: 757d03a9d56f
Create Date: 2024-03-13 22:18:23.407083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d9e109ab04b'
down_revision: Union[str, None] = '757d03a9d56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_balance', sa.Float(), nullable=False),
    sa.Column('init_deposit', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='positionstatus'), nullable=False),
    sa.Column('trade_start_date', sa.DateTime(), nullable=False),
    sa.Column('pending_withdrawal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vaults', sa.Column('contract_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vaults', sa.Column('current_round', sa.Integer(), nullable=True))
    op.add_column('vaults', sa.Column('next_close_round_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'next_close_round_date')
    op.drop_column('vaults', 'current_round')
    op.drop_column('vaults', 'contract_address')
    op.drop_table('user_portfolio')
    op.execute('DROP TYPE IF EXISTS positionstatus')
    # ### end Alembic commands ###
