"""Updae RewardSessionConfig duration_in_minutes

Revision ID: 5cc6cf68ef68
Revises: 704bde43cc09
Create Date: 2024-06-22 21:58:30.371580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc6cf68ef68'
down_revision: Union[str, None] = '704bde43cc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_session_config', sa.Column('duration_in_minutes', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('reward_session_config', 'start_delay_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_session_config', sa.Column('start_delay_days', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.drop_column('reward_session_config', 'duration_in_minutes')
    # ### end Alembic commands ###
