"""Add points_ditributed to RewardSession table

Revision ID: 704bde43cc09
Revises: d07ca5ed31cb
Create Date: 2024-06-20 15:13:05.522331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704bde43cc09'
down_revision: Union[str, None] = 'd07ca5ed31cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_sessions', sa.Column('points_distributed', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reward_sessions', 'points_distributed')
    # ### end Alembic commands ###
