"""Init vault PPS history model

Revision ID: 757d03a9d56f
Revises: 3533c6e4d016
Create Date: 2024-03-09 16:06:41.897478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '757d03a9d56f'
down_revision: Union[str, None] = '3533c6e4d016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pps_history',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('price_per_share', sa.Float(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('vault_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pps_history')
    # ### end Alembic commands ###
