"""create_price_feed_oracle_table

Revision ID: a24a82767f1e
Revises: 5f35910be538
Create Date: 2024-05-08 22:54:52.545508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a24a82767f1e'
down_revision: Union[str, None] = '5f35910be538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
      # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_feed_oracle_history',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('token_pair', sa.String(length=256), nullable=False),
    sa.Column('latest_price', sa.Float(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
     # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_feed_oracle_history')
    # ### end Alembic commands ###
