"""Added UserPoints models

Revision ID: b3593cef3d00
Revises: a24a82767f1e
Create Date: 2024-05-15 08:53:57.423006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b3593cef3d00"
down_revision: Union[str, None] = "a24a82767f1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


VaultCategory = sa.Enum("real_yield", "points", name="vaultcategory", create_type=False)
NetworkChain = sa.Enum(
    "ethereum",
    "bsc",
    "arbitrum_one",
    "base",
    "blast",
    name="networkchain",
    create_type=False,
)


def upgrade() -> None:
    # Create the Enum types in the database
    VaultCategory.create(op.get_bind(), checkfirst=False)
    NetworkChain.create(op.get_bind(), checkfirst=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "point_distribution_history",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("partner_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("point", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_point_distribution_history_created_at"),
        "point_distribution_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_point_distribution_history_partner_name"),
        "point_distribution_history",
        ["partner_name"],
        unique=False,
    )
    op.create_table(
        "user_points",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("wallet_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("partner_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_points_created_at"), "user_points", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_points_partner_name"),
        "user_points",
        ["partner_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_points_updated_at"), "user_points", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_points_wallet_address"),
        "user_points",
        ["wallet_address"],
        unique=False,
    )
    op.create_table(
        "user_point_audit",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_points_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("old_value", sa.Float(), nullable=False),
        sa.Column("new_value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_points_id"],
            ["user_points.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "vaults", sa.Column("routes", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "vaults",
        sa.Column(
            "category",
            sa.Enum("real_yield", "points", name="vaultcategory"),
            nullable=True,
        ),
    )
    op.add_column(
        "vaults",
        sa.Column(
            "network_chain",
            sa.Enum(
                "ethereum", "bsc", "arbitrum_one", "base", "blast", name="networkchain"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vaults", "network_chain")
    op.drop_column("vaults", "category")
    op.drop_column("vaults", "routes")
    op.drop_table("user_point_audit")
    op.drop_index(op.f("ix_user_points_wallet_address"), table_name="user_points")
    op.drop_index(op.f("ix_user_points_updated_at"), table_name="user_points")
    op.drop_index(op.f("ix_user_points_partner_name"), table_name="user_points")
    op.drop_index(op.f("ix_user_points_created_at"), table_name="user_points")
    op.drop_table("user_points")
    op.drop_index(
        op.f("ix_point_distribution_history_partner_name"),
        table_name="point_distribution_history",
    )
    op.drop_index(
        op.f("ix_point_distribution_history_created_at"),
        table_name="point_distribution_history",
    )
    op.drop_table("point_distribution_history")

    # Drop the Enum types from the database
    VaultCategory.drop(op.get_bind(), checkfirst=False)
    NetworkChain.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
